### Vista de todos los clientes
GET http://localhost:9999/api/v1/cliente
Content-Type: application/json
Accept: application/json

### Vista detallada de todos los clientes
GET http://localhost:9999/api/v1/cliente/clientes
Content-Type: application/json
Accept: application/json

### Crear Cliente
POST http://localhost:9999/api/v1/cliente/create
Content-Type: application/json
Accept: application/json

{
    "correo": "Juan@asasd",
    "password": "Perez",
    "estadoCuenta": "Activo",
    "idPersona": 1
}

### login
POST http://localhost:9999/api/v1/cliente/login
Content-Type: application/json
Accept: application/json

{
    "correo": "Juan@asasd",
    "password": "Perez"
}

### Modificar cliente
PUT http://localhost:9999/api/v1/cliente/update/2
Content-Type: application/json
Accept: application/json

{
    "correo": "Juan@asasdsss",
    "password": "Perezzzz",
    "estadoCuenta": "Activo",
    "idPersona": 1
}

### Eliminar cliente
DELETE http://localhost:9999/api/v1/cliente/delete/2
Content-Type: application/json
Accept: application/json
